.TH "connectPsql" 3 "Wed Apr 24 2019" "Jobber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connectPsql \- The \fBconnectPsql\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <connectpsql\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnectPsql\fP (QString windowTitle, QWidget *parent=0)"
.br
.RI "\fBconnectPsql::connectPsql\fP Class constructor "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpsql\fP * \fBp\fP"
.br
.RI "p A PostgreSQL pointer "
.in -1c
.SH "Detailed Description"
.PP 
The \fBconnectPsql\fP class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "connectPsql::connectPsql (QString windowTitle, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBconnectPsql::connectPsql\fP Class constructor 
.PP
\fBParameters:\fP
.RS 4
\fIwindowTitle\fP The title to be used in message boxes, etc\&. 
.br
\fIparent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobber from the source code\&.
