.TH "MainWindow" 3 "Thu Sep 20 2018" "Jobber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- The \fBMainWindow\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.RI "\fBMainWindow\fP Class constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconnectPsql\fP * \fBcp\fP"
.br
.RI "cp A pointer to the \fBconnectPsql\fP class "
.in -1c
.SH "Detailed Description"
.PP 
The \fBMainWindow\fP class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBMainWindow\fP Class constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobber from the source code\&.
