.TH "newcity.cpp" 3 "Wed Apr 24 2019" "Jobber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
newcity.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'newcity\&.h'\fP
.br
\fC#include 'ui_newcity\&.h'\fP
.br
\fC#include <QPushButton>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobber from the source code\&.
