.TH "NewJob" 3 "Tue Jun 11 2019" "Jobber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewJob \- The \fBNewJob\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <newjob\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewJob\fP (QString windowTitle, \fBpsql\fP *pg, QWidget *parent=0)"
.br
.RI "\fBNewJob\fP The \fBNewJob\fP class constructor\&. "
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *event) override"
.br
.RI "closeEvent Code to be executed when the window closes "
.in -1c
.SH "Detailed Description"
.PP 
The \fBNewJob\fP class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewJob::NewJob (QString windowTitle, \fBpsql\fP * pg, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBNewJob\fP The \fBNewJob\fP class constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwindowTitle\fP The title to be used in message boxes and other things\&. 
.br
\fIpg\fP A pointer to the PostgreSQL database\&. 
.br
\fIparent\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void NewJob::closeEvent (QCloseEvent * event)\fC [override]\fP"

.PP
closeEvent Code to be executed when the window closes 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP This pointer points to the QCloseEvent class that contains functions to prvent the window from closing\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobber from the source code\&.
