.TH "stringCheck" 3 "Fri Feb 8 2019" "Jobber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stringCheck
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBisNullOrWhitespace\fP (QString string)"
.br
.RI "\fBstringCheck::isNullOrWhitespace\fP Checks if the string is empty or if it only contains whitespaces\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool stringCheck::isNullOrWhitespace (QString string)\fC [static]\fP"

.PP
\fBstringCheck::isNullOrWhitespace\fP Checks if the string is empty or if it only contains whitespaces\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP The string in question 
.RE
.PP
\fBReturns:\fP
.RS 4
True if the string is empty or only contains whitespaces\&. Returns false otherwise\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobber from the source code\&.
