.TH "newcity.cpp" 3 "Wed Feb 7 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
newcity.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'newcity\&.h'\fP
.br
\fC#include 'ui_newcity\&.h'\fP
.br
\fC#include <QPushButton>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
