.TH "SpesificJobs" 3 "Thu Jan 4 2018" "Jobber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpesificJobs
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpesificJobs\fP (QString title, \fBpsql\fP *pg, QWidget *parent=0)"
.br
.ti -1c
.RI "QString \fBgetJobTitle\fP ()"
.br
.ti -1c
.RI "QString \fBgetCompanyName\fP ()"
.br
.ti -1c
.RI "QString \fBgetCityName\fP ()"
.br
.ti -1c
.RI "QString \fBgetStatus\fP ()"
.br
.ti -1c
.RI "QString \fBgetDeadline\fP ()"
.br
.ti -1c
.RI "QString \fBgetMotivation\fP ()"
.br
.ti -1c
.RI "void \fBsetJobTitle\fP (QString newTitle)"
.br
.ti -1c
.RI "void \fBsetCompanyName\fP (QString newName)"
.br
.ti -1c
.RI "void \fBsetCityName\fP (QString newCityName)"
.br
.ti -1c
.RI "void \fBsetStatus\fP (QString newStatus)"
.br
.ti -1c
.RI "void \fBsetDeadline\fP (QString newDeadline)"
.br
.ti -1c
.RI "void \fBsetMotivation\fP (QString newMotivation)"
.br
.ti -1c
.RI "void \fBgetCityNames\fP ()"
.br
.ti -1c
.RI "void \fBgetStatuses\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobber from the source code\&.
