.TH "statistics" 3 "Wed Feb 7 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statistics
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatistics\fP (\fBpsql\fP *pg, QWidget *parent=0)"
.br
.RI "\fBstatistics::statistics\fP statisitcs class constructor\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "statistics::statistics (\fBpsql\fP * pg, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBstatistics::statistics\fP statisitcs class constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpg\fP The pointer to the psql class 
.br
\fIparent\fP Pointer the the parent class 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
