all:

install:
	install -g wheel -o root -m 755 updateports.sh /usr/sbin/updateports
	install -g wheel -o root -m 755 updateports.1 /usr/share/man/man1/updateports.1

deinstall:
	rm /usr/sbin/updateports /usr/share/man/man1/updateports.1

uninstall:
	rm /usr/sbin/updateports /usr/share/man/man1/updateports.1
