UNAME_S != uname
updateports:
	@echo ${UNAME_S}
.if exists(/usr/bin/xdotool)
	cc --std=c11 -o updateports updateports.c
.else
.if exists(/usr/local/bin/xdotool)
	cc --std=c11 -o updateports updateports.c
.else
.error File does /usr/local/bin/xdotool or /usr/bin/xdotool does not exist
.endif
.endif

install: updateports
.if (${UNAME_S} == "Linux")
	install -o root -g root updateports /usr/local/sbin/updateports
	install -o root -g root updateports.8 /usr/share/man/man8/updateports.8
.else
	install -o root -g wheel updateports /usr/local/sbin/updateports
	install -o root -g wheel rmoldpackages_updateports.sh /usr/local/sbin/rmoldpackages_updateports
	install -o root -g wheel updateports.8 /usr/local/man/man8/updateports.8
.endif

clean:
	rm -f updateports
uninstall:
	rm -f /usr/local/sbin/updateports
	rm -f /usr/local/sbin/rmoldpackages_updateports
.if (${UNAME_S} == "Linux")
	/usr/share/man/man8/updateports.8
.else
	rm -f /usr/local/man/man8/updateports.8
.endif
deinstall:
	rm -f /usr/local/sbin/updateports
	rm -f /usr/local/sbin/rmoldpackages_updateports
.if (${UNAME_S} == "Linux")
	/usr/share/man/man8/updateports.8
.else
	rm -f /usr/local/man/man8/updateports.8
.endif
